### ISSUE TITLE
ember-responsive-image v2 breaks Casper template

### ISSUE THREAD

**Issue by elwayman02** [empress/empress-blog-casper-template#39]
Got the following production error when upgrading ember-responsive-image in my app:

> Uncaught (in promise) TypeError: Cannot read property 'charAt' of undefined

The build also threw this:

> WARNING: Could not find config for ember-responsive-image, skipping image processing...

I believe this has to do with the migration to Octane, per the following error in the terminal output:

> Error: Assertion Failed: No image argument supplied for <ResponsiveImage>

**Comment by elwayman02** [comment]
There's a fairly lengthy migration guide for this addon: https://github.com/kaliber5/ember-responsive-image/blob/master/docs/MIGRATION.md

**Comment by elwayman02** [comment]
Here's a branch that can be checked out for basic repro: https://github.com/empress/empress-blog-casper-template/compare/master...elwayman02:responsive-2.0

**Comment by MichalBryxi** [comment]
Just got burned by this again. If there is no easy fix, can we simply lock the version of `ember-responsive-image` on `v1.x`? I can't find where that comes from?

**Comment by elwayman02** [comment]
Fixed by #37 & #45
